version: '3.7'

services:
  diyanfebri:
    build: 
      context: .
    command: sh -c "bundle exec jekyll serve --trace --incremental"
    expose:
      - 4000
    volumes:
      - .:/diyanfebri
  
  nginx:
    build: ./nginx
    volumes:
      - .:/nginx/etc/nginx/conf.d/
    ports:
      - 4000:80
    depends_on:
      - diyanfebri
